[tool.poetry]
name = "components"
version = "0.1.0"
description = ""
authors = ["Jason Montgomery <j.monty@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
eidolon-ai-sdk = "^0.1.83"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
